Name:           ros-jade-pid
Version:        0.0.17
Release:        0%{?dist}
Summary:        ROS pid package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/pid
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-jade-diagnostic-updater
Requires:       ros-jade-dynamic-reconfigure
Requires:       ros-jade-message-runtime
Requires:       ros-jade-roscpp
Requires:       ros-jade-std-msgs
BuildRequires:  ros-jade-catkin
BuildRequires:  ros-jade-diagnostic-updater
BuildRequires:  ros-jade-dynamic-reconfigure
BuildRequires:  ros-jade-message-generation
BuildRequires:  ros-jade-roscpp
BuildRequires:  ros-jade-std-msgs

%description
Launch a PID control node.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/jade" \
        -DCMAKE_PREFIX_PATH="/opt/ros/jade" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/jade

%changelog
* Mon Aug 22 2016 Andy Zelenak <andyz@utexas.edu> - 0.0.17-0
- Autogenerated by Bloom

* Fri Aug 19 2016 Andy Zelenak <andyz@utexas.edu> - 0.0.16-0
- Autogenerated by Bloom

* Mon Feb 22 2016 Andy Zelenak <andyz@utexas.edu> - 0.0.15-0
- Autogenerated by Bloom

* Wed Feb 17 2016 Andy Zelenak <andyz@utexas.edu> - 0.0.14-0
- Autogenerated by Bloom

* Mon Feb 01 2016 Andy Zelenak <andyz@utexas.edu> - 0.0.13-0
- Autogenerated by Bloom

* Wed Jan 20 2016 Andy Zelenak <andyz@utexas.edu> - 0.0.12-1
- Autogenerated by Bloom

* Tue Jan 05 2016 Andy Zelenak <andyz@utexas.edu> - 0.0.12-0
- Autogenerated by Bloom

* Mon Jan 04 2016 Andy Zelenak <andyz@utexas.edu> - 0.0.11-0
- Autogenerated by Bloom

* Sun Dec 27 2015 Andy Zelenak <andyz@utexas.edu> - 0.0.9-0
- Autogenerated by Bloom

* Sun Jul 26 2015 Andy Zelenak <andyz@utexas.edu> - 0.0.7-0
- Autogenerated by Bloom

* Tue Jun 09 2015 Andy Zelenak <andyz@utexas.edu> - 0.0.6-0
- Autogenerated by Bloom

* Tue Jun 09 2015 Andy Zelenak <andyz@utexas.edu> - 0.0.5-0
- Autogenerated by Bloom

* Sat Jun 06 2015 Andy Zelenak <andyz@utexas.edu> - 0.0.4-0
- Autogenerated by Bloom

* Sat Jun 06 2015 Andy Zelenak <andyz@utexas.edu> - 0.0.3-0
- Autogenerated by Bloom

